### ISSUE TITLE
Correcciones y consejos

### ISSUE THREAD

**Issue by Liluminalia** [Fabioo798/202301-W3CH5-FabioDiNoia#6]
Buenas Fabio!, esta genial, igual habría que mirar el tamaño de esos botones en proporción al pokemon 😅 nada, es broma, son detalles estéticos, y de momento no nos importan, esta genial.

intenta revisar los commits un poco, en general están muy bien, pero aun faltan cosillas, tiendes a poner el gerundio (-ing, Installing, creating, updating...), intenta ponerlos en imperativo (Install, Create, Update, Add, Fix...), falta muy poco para que estén perfect, revisa los comentarios que te he puesto en algunos commits y bueno luego el testing no esta mal, asi que nada mucho animo y a seguir asi!! 

pd: échale un ojo tambien al sonar, esta genial que han bajado los code smells (es lo que hay que hacer, antes de seguir avanzando con la programación si vemos smells o bugs, corregirlos) pero hay que intentar dejarlos a cero! animo!

**Comment by Fabioo798** [comment]
vale, gracias por los feedback, ententare mejorar lo de las ramas y de lo que ago en ella, es que cuando tengo poco tiempo empiezo a a juntar todo 😆

**Comment by Liluminalia** [comment]
tu y todos! jaja tranqui que es normal, poco a poco se va mejorando con la practica! cierro el issue!
